### ISSUE TITLE
Option to unzip password protected file - code diff included

### ISSUE THREAD

**Issue by itsrobli** [google/ripunzip#62]
Hi there

I'm loving this library! 😃 

I have a couple of use cases not implemented and wondering if this project is interested in my contributing it back, or if I should just continue with my fork.

1. Is this [diff](https://github.com/google/ripunzip/compare/main...itsrobli:ripunzip-put:feature/password-protected-zip) I've just done to allow for unzipping of password protected files.

My diff is minimally tested and documented for now so you can understand the change. If this project is interested in the contribution, I will put the effort in to get it up to standard. Otherwise, no worries! I'm happy either way.

2. Is probably out of scope of this project, but I'll mention it anyway in case, since I'll start working on it soon-ish
 
My use case is that I have a data pipeline that unzips many files each day. The unzipped contents is of an unknown size but large (many TBs) and varies from file to file. I don't want to unzip it in the executing machine, but instead, stream it directly to cloud storage e.g. AWS S3. The goal is, it ensures the machine running the unzipping operation can be minimal in storage requirements.

This library currently outputs to local file storage only (I could be wrong!). But it reads from both local and HTTPS locations. So I thought it would be cool if it could also write to a non-local location.

Thanks for your work and time reading this!

**Comment by adetaylor** [comment]
Sorry for not noticing this till now, for some reason github hasn't been emailing me about all these raised issues and I hadn't noticed that people started to pay attention to this project :)

Yes I'd be happy to accept a pull request for the password option.

For the second request, I don't think we want to support writing to non-filesystem locations in general, but I'd be happy to accept a pull request for #27 which would give you more options here.

**Comment by fujiyamaorange** [comment]
@itsrobli 
Hello!

I've been wanting this feature lately too!
If you would be willing to create a PR I would be greatly appreciated!

**Comment by itsrobli** [comment]
Hey thanks for the feedback @adetaylor. Yeah I’ll take up this password option. Not sure exactly when yet. I’ll keep this issue updated on my progress.

**Comment by adetaylor** [comment]
Awesome!

**Comment by itsrobli** [comment]
Ok I’ve submitted a PR. Just needs a maintainer to kick off the build workflow.
