### ISSUE TITLE
Disk usage during decompression

### ISSUE THREAD

**Issue by thvasilo** [google/ripunzip#85]
Hi thanks for the great tool!

I was wondering what the expectation should be for disk usage during decompression. 

I'm trying to use ripunzip to decompress a ~60GB file (available [here](http://snap.stanford.edu/ogb/data/nodeproppred/papers100M-bin.zip)), that contains one file that's around 54GB (a zip file itself, in the form of a numpy npz archive). 

During decompression I see my disk usage slowly climb up to 190GB. I would expect it to be around 60+70ish for the decompressed data, is more disk being used during decompression?

**Comment by adetaylor** [comment]
That is a bit surprising. Can you give the command you used to unzip? (Specifically I'm interested in whether you unzipped via HTTP or locally, but giving me your exact command increases the chances I'll reproduce the oddity)

**Comment by thvasilo** [comment]
Hi turns out the decompressed files were much larger than I anticipated which was causing the discrepancy, nothing to do with ripunzip :)

**Comment by adetaylor** [comment]
Thanks for letting me know!
